#!/bin/bash

echo "🔐 GitHub Secrets Setup for Multi-Registry Publishing"
echo "====================================================="

echo ""
echo "This workflow now publishes to multiple registries:"
echo "🐳 Docker Hub + GitHub Container Registry"
echo "📦 npmjs.org + GitHub Packages npm"
echo ""

echo "📋 Required GitHub Secrets:"
echo "=========================="
echo ""

echo "1. DOCKER_USERNAME (Docker Hub)"
echo "   ├── Name: DOCKER_USERNAME"
echo "   ├── Value: windbit"
echo "   └── Purpose: Docker Hub authentication"
echo ""

echo "2. DOCKER_PASSWORD (Docker Hub)"
echo "   ├── Name: DOCKER_PASSWORD"
echo "   ├── Value: [Your Docker Hub access token]"
echo "   ├── Create at: https://hub.docker.com/settings/security"
echo "   ├── Permissions: Read, Write, Delete"
echo "   └── Purpose: Docker Hub publishing"
echo ""

echo "3. NPM_TOKEN (npmjs.org)"
echo "   ├── Name: NPM_TOKEN"
echo "   ├── Value: [Your npm access token]"
echo "   ├── Create at: https://www.npmjs.com/settings/tokens"
echo "   ├── Type: Automation token (or Classic with Publish permissions)"
echo "   └── Purpose: npm package publishing to npmjs.org"
echo ""

echo "4. GITHUB_TOKEN (Automatic)"
echo "   ├── Name: GITHUB_TOKEN"
echo "   ├── Value: [Automatically provided by GitHub Actions]"
echo "   ├── Purpose: GitHub Container Registry + GitHub Packages"
echo "   └── Note: No manual setup required"
echo ""

echo "🔧 Step-by-Step Setup:"
echo "======================"
echo ""

echo "STEP 1: Create Docker Hub Access Token"
echo "--------------------------------------"
echo "1. Go to: https://hub.docker.com/settings/security"
echo "2. Click 'New Access Token'"
echo "3. Description: 'GitHub Actions youtrack-mcp'"
echo "4. Permissions: 'Read, Write, Delete'"
echo "5. Copy the token (starts with dckr_pat_...)"
echo ""

echo "STEP 2: Create npm Access Token"
echo "-------------------------------"
echo "1. Go to: https://www.npmjs.com/settings/tokens"
echo "2. Click 'Generate New Token'"
echo "3. Type: 'Automation' (recommended) or 'Classic'"
echo "4. If Classic: Select 'Publish' permission"
echo "5. Copy the token (starts with npm_...)"
echo ""

echo "STEP 3: Add Secrets to GitHub Repository"
echo "----------------------------------------"
echo "1. Go to: https://github.com/windbit/agentek-youtrack-mcp/settings/secrets/actions"
echo "2. Click 'New repository secret' for each:"
echo ""
echo "   DOCKER_USERNAME:"
echo "   ├── Secret Name: DOCKER_USERNAME"
echo "   └── Secret Value: windbit"
echo ""
echo "   DOCKER_PASSWORD:"
echo "   ├── Secret Name: DOCKER_PASSWORD"
echo "   └── Secret Value: [Docker Hub token from Step 1]"
echo ""
echo "   NPM_TOKEN:"
echo "   ├── Secret Name: NPM_TOKEN"
echo "   └── Secret Value: [npm token from Step 2]"
echo ""

echo "✅ Verification Checklist:"
echo "=========================="
echo ""
echo "After adding all secrets, verify in GitHub:"
echo "├── DOCKER_USERNAME ✓"
echo "├── DOCKER_PASSWORD ✓"
echo "├── NPM_TOKEN ✓"
echo "└── GITHUB_TOKEN ✓ (automatic)"
echo ""

echo "🚀 What Happens After Setup:"
echo "==========================="
echo ""
echo "📦 On Every Main Branch Push:"
echo "├── Build & test code"
echo "├── Publish Docker images:"
echo "│   ├── windbit/agentek-youtrack-mcp:{version}_wip"
echo "│   └── ghcr.io/windbit/agentek-youtrack-mcp:{version}_wip"
echo "└── Skip npm publishing (only on releases)"
echo ""

echo "🎉 On Every GitHub Release:"
echo "├── Build & test code"
echo "├── Publish Docker images:"
echo "│   ├── windbit/agentek-youtrack-mcp:latest"
echo "│   ├── windbit/agentek-youtrack-mcp:{version}"
echo "│   ├── ghcr.io/windbit/agentek-youtrack-mcp:latest"
echo "│   └── ghcr.io/windbit/agentek-youtrack-mcp:{version}"
echo "├── Publish npm packages:"
echo "│   ├── agentek-youtrack-mcp@{version} (npmjs.org)"
echo "│   └── @windbit/agentek-youtrack-mcp@{version} (GitHub Packages)"
echo "└── Update package.json version automatically"
echo ""

echo "🔍 Testing Your Setup:"
echo "======================"
echo ""
echo "1. Verify secrets are added correctly in GitHub"
echo "2. Push a commit to main branch"
echo "3. Check GitHub Actions workflow run"
echo "4. Verify Docker images appear in both registries"
echo "5. Create a release to test npm publishing"
echo ""

echo "📚 Registry URLs:"
echo "================"
echo ""
echo "Docker Hub:"
echo "└── https://hub.docker.com/r/windbit/agentek-youtrack-mcp"
echo ""
echo "GitHub Container Registry:"
echo "└── https://github.com/windbit/agentek-youtrack-mcp/pkgs/container/youtrack-mcp"
echo ""
echo "npmjs.org:"
echo "└── https://www.npmjs.com/package/agentek-youtrack-mcp"
echo ""
echo "GitHub Packages npm:"
echo "└── https://github.com/windbit/agentek-youtrack-mcp/pkgs/npm/%40windbit%2Fagentek-youtrack-mcp"
echo ""

echo "💡 Pro Tips:"
echo "============"
echo ""
echo "✅ Use automation tokens for npm (more secure)"
echo "✅ Docker Hub tokens are preferable to passwords"
echo "✅ GITHUB_TOKEN is automatically available, no setup needed"
echo "✅ GitHub Container Registry uses GITHUB_TOKEN (free)"
echo "✅ Both Docker registries will have identical content"
echo "✅ Both npm registries will have identical functionality"
echo "⚠️  npm packages only publish on GitHub releases, not main pushes"
echo "⚠️  Keep your tokens secure and rotate them periodically"
echo ""

echo "🎯 Next Steps:"
echo "=============="
echo "1. Complete the token setup above"
echo "2. Verify all 3 secrets are added to GitHub"
echo "3. Push a commit to test Docker image publishing"
echo "4. Create a release to test npm package publishing"
echo "5. Update your documentation with new registry options" 